In [5]:
import numpy as np
import matplotlib.pyplot as plt
import torch
import pandas as pd
from torch.utils.data import Dataset


In [3]:
a = torch.tensor([[1,2,3] , [4,5,6], [7,8,9]])

a

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [4]:
b = torch.tensor([[1,2,3] , [4,5,6], [7,8,9]])

b

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [13]:
c = a *b
c.ndim , a.size() , a.numel()

(2, torch.Size([3, 3]), 9)

In [14]:
tensor_example = torch.tensor([[11, 12, 13], [21, 22, 23], [31, 32, 33]])
print("What is the value on 2nd-row 3rd-column? ", tensor_example[1, 2])
print("What is the value on 2nd-row 3rd-column? ", tensor_example[1][2])

What is the value on 2nd-row 3rd-column?  tensor(23)
What is the value on 2nd-row 3rd-column?  tensor(23)


In [20]:
tensor_example

tensor([[11, 12, 13],
        [21, 22, 23],
        [31, 32, 33]])

In [21]:
tensor_example[2,0:3]

tensor([31, 32, 33])

**Drivatives**

In [40]:
X= torch.tensor(2.0,requires_grad=True)
X

tensor(2., requires_grad=True)

In [41]:
y = X**2
y.backward()
X.grad

tensor(4.)

In [34]:
x = torch.tensor(2.0,requires_grad=True)
z = x**2 + 2*x + 1
z.backward()
x.grad

tensor(6.)

In [2]:
u = torch.tensor(1.0,requires_grad=True)
v = torch.tensor(2.0,requires_grad=True)
f = u*v + u**2
f.backward()
u.grad
v.grad

tensor(1.)

In [35]:
x = torch.tensor(4.0,requires_grad=True)
y = x**2


In [36]:
x ,y

(tensor(4., requires_grad=True), tensor(16., grad_fn=<PowBackward0>))

In [37]:
z = torch.sin(y)

In [38]:
z.backward()
x.grad

tensor(-7.6613)

tensor(4.)

In [27]:
y = torch.tensor(y , requires_grad=True)
z = torch.sin(y)
z.backward()
y.grad

<ipython-input-27-2882620f084f>:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y = torch.tensor(y , requires_grad=True)


tensor(-0.6536)